### ISSUE TITLE
[Bug] Not working on window cmd terminal

### ISSUE THREAD

**Issue by sujang958** [KimbabKR/create-discord-bots#2]
```
yarn global add create-discord-bots
```
```
create-discord-bots asdf
```
***error***
'create-discord-bots'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.

**사양**
* NPM 버전 : 6.13.4
* Node.js 버전 : 12.14.1
* 사용하는 컴퓨터 : Samsung Laptop
* Yarn 버전 : 1.22.10

**Comment by MadeGOD** [comment]
해당 문제는 버그가 아닙니다. 아래 명령어를 사용하셔야 모듈관련 동시에 작동됩니다.

```sh
npx create-discord-bots
```
